language: python
python:
  - "3.8"
  - "pypy3"

install:
  - pip3 install -r requirements.txt

run: apt-get update
run: apt-get install software-properties-common -y
run: apt-get install gnupg2 -y
run: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 3B4FE6ACC0B21F32
run: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 871920D1991BC93C
run: add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ focal main restricted"
run: apt-get update
run: apt-get install wget -y
run: apt-get install firefox -y
run: wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
run: tar -xvzf geckodriver*
run: chmod +x geckodriver
run: mv geckodriver /usr/local/bin/

script: pytest

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY

  region: "sa-east-1"
  app: "stockprices-prediction"
  env: "stockprices-predction"
  bucket_name: "elastick-beanstalk"