language: python
python:
  - "3.8"
  - "pypy3"

before_install:
  - apt-get update
  - apt-get install software-properties-common -y
  - apt-get install gnupg2 -y
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 3B4FE6ACC0B21F32
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 871920D1991BC93C
  - add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ focal main restricted"
  - apt-get update
  - apt-get install wget -y
  - apt-get install firefox -y
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - tar -xvzf geckodriver*
  - chmod +x geckodriver
  - mv geckodriver /usr/local/bin/

install:
  - pip3 install -r requirements.txt

script: pytest

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY

  region: "sa-east-1"
  app: "stockprices-prediction"
  env: "stockprices-predction"
  bucket_name: "elastick-beanstalk"